### PR TITLE
SIGNAL SET MESSAGE_TEXT from stored procedure does not get pass on

### PR DESCRIPTION
**Pull request by outbackStack**
I would like to access the MESSAGE_TEXT variable from the stored procedure if possible.

### CODE REVIEW

**Comment by outbackStack** [comment]
for some reasons the 'msg' key is coming back with the sql as well and not just the MESSAGE_TEXT

```js
{
  msg: 'not working\n' +
    "sql: CALL test_error(1) - parameters:[1]",
  fatal: false,
  errno: 1644,
  sqlState: '45000',
  code: 'ER_SIGNAL_EXCEPTION'
}
```

**Comment by outbackStack** [comment]
```sql
CREATE PROCEDURE test_error(x INT)
BEGIN
   IF x = 1 THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'not working';
   END IF;
END;
```

then using node
```js
const mariadb = require('mariadb');
const pool = mariadb.createPool({host: process.env.DB_HOST, user: process.env.DB_USER, connectionLimit: 5});

async function asyncFunction() {
  let conn;
  try {
	conn = await pool.getConnection();
	const res = await conn.query("CALL test_error(1)");

  } catch (err) {
	console.log(err)
  }
}
```

console.log(error) only print out the following:

```json
  fatal: false,
  errno: 1644,
  sqlState: '45000',
  code: 'ER_SIGNAL_EXCEPTION'
```

I would like to access the MESSAGE_TEXT' variable from catch error.

**Comment by rusher** [comment]
SqlError extends [Error](https://nodejs.org/api/errors.html#errors_new_error_message).
Error message is available using Error.message.

Driver add some information in message returning something like `(conn=5149, no: 1644, SQLState: 45000) not working` for better identification.

**Comment by outbackStack** [comment]
Hi rusher,

Error.message gives me the following
`(conn=586, no: 1644, SQLState: 45000) not working.
sql: CALL test_error(?) - parameters:['1]`

error.msg still gives me the driver info but I can split the text into two parts so I could just extract the MESSAGE_TEXT. Not sure if there's an easier way

**Comment by rusher** [comment]
It make sense. i've created https://jira.mariadb.org/projects/CONJS/issues/CONJS-165.
Additionally to your current PR, it has to be added to typescript definition and have according test.

**Comment by outbackStack** [comment]
ok I've added in the typescript definition. Hope that is all good. 😀 Not sure how I could do the test though

**Comment by outbackStack** [comment]
actually, if the fix with CONJS-165  can be done with `error.message` then we don't need this. I can close this PR to make it easier.

**Comment by rusher** [comment]
no, this way is better. 
Most of the time, when an error is logged, it's better to have a complete message (that comes from Error.message value), but having separately real message error on object make sense.

**Comment by rusher** [comment]
merged in develop branch. Will be in next release

**Comment by outbackStack** [comment]
I didn't realised so many files need to be changed for this but thank you :-)

**Pull request closed without merging**
